name: Build and Publish Proxy Image
on:
  push:
    branches:
      - master
      - BAH-1439
    paths:
      - "bahmni-proxy/**"
      - ".github/workflows/build_publish_proxy.yml"
env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: bahmni-proxy/docker/Dockerfile
          push: true
          tags: bahmniindiadistro/bahmni-proxy-abdm:${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmniindiadistro/bahmni-proxy-abdm

