name: Build and Publish Bahmni-Web
on:
  push:
    branches:
      - main
    paths:
      - "bahmni-web/**"
      - ".github/workflows/build_publish_web.yml"
  workflow_dispatch:

  repository_dispatch:
    types: [ "clinic-config-trigger"  ]

jobs:
  docker-build-publish:
    name: Docker Build & Publish bahmni-web
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: bahmni-web/package/helm/
    steps:
      - uses: actions/checkout@v2
      - name: Download clinic_config.zip
        run: sh .github/download_artifact.sh clinic-config ClinicConfig ${{secrets.BAHMNI_PAT}} bahmni-web
      - name: Download ndhm-react.zip
        run: sh .github/download_artifact.sh ndhm-react NDHMReact ${{secrets.BAHMNI_PAT}} bahmni-web
      - name: Setting Artifact version
        run: |
          APP_VERSION=$(cat bahmni-web/.appversion)
          echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bahmni-web/package/docker/Dockerfile
          push: true
          tags: bahmniindiadistro/bahmni-web:${{env.ARTIFACT_VERSION}},bahmniindiadistro/bahmni-web:latest
      - name: Helm - Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: Bahmniindiadistro/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/bahmni-web/ && cp bahmni-web-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/bahmni-web/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmniindiadistro.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of bahmni-web-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmniindiadistro/helm-charts.git' gh-pages
