name: Build and Publish Bahmni-Web
on:
  push:
    branches: [master,BAH-1439]
    paths:
      - ".github/workflows/build_publish_web.yml"
      - "bahmni-web/docker/Dockerfile"

  repository_dispatch:
    types: [ "default-config-trigger", "ndhm-react-trigger" ]

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish bahmni-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download default_config.zip
        run: sh .github/download_artifact.sh default-config DefaultConfig ${{secrets.BAHMNI_INDIADISTRO_PAT}} bahmni-web
      - name: Download ndhm-react.zip
        run: sh .github/download_artifact.sh ndhm-react NDHMReact ${{secrets.BAHMNI_INDIADISTRO_PAT}} bahmni-web
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bahmni-web/docker/Dockerfile
          push: true
          tags: bahmniindiadistro/bahmni-web-abdm:${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmniindiadistro/bahmni-web-abdm
